---
build_from:
  aarch64: ghcr.io/muthur-command/aarch64-base-python:3.13-alpine3.22
  amd64: ghcr.io/muthur-command/amd64-base-python:3.13-alpine3.22
  armhf: ghcr.io/muthur-command/armhf-base-python:3.13-alpine3.22
  armv7: ghcr.io/muthur-command/armv7-base-python:3.13-alpine3.22
  i386: ghcr.io/muthur-command/i386-base-python:3.13-alpine3.22
args:
  UNIVERSAL_SILABS_FLASHER: 0.0.36
