---
build_from:
  aarch64: ghcr.io/muthur-command/aarch64-base:3.22
  amd64: ghcr.io/muthur-command/amd64-base:3.22
  armv7: ghcr.io/muthur-command/armv7-base:3.22
  i386: ghcr.io/muthur-command/i386-base:3.22
