---
version: 1.4.3
slug: speech-to-phrase
name: Speech-to-Phrase
description: Fast and personalized local speech-to-text
url: http://github.com/OHF-voice/speech-to-phrase
arch:
  - amd64
  - aarch64
init: false
discovery:
  - wyoming
map:
  - share:rw
backup_exclude:
  - "*/models/*"
muthurcommand_api: true
options:
  debug_logging: false
schema:
  debug_logging: bool
ports:
  "10300/tcp": null
muthurcommand: 2023.11.0
image: muthur-command/{arch}-addon-speech-to-phrase
